#include "httplib.h"
#include "vector_db.h"

#include <ctime>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <stdexcept>


// =========================================================
// Parse comma-separated vector
// =========================================================

std::vector<float> parseVector(
    const std::string& input
) {

    std::vector<float> result;

    std::stringstream ss(input);
    std::string value;

    while (std::getline(ss, value, ',')) {

        if (!value.empty()) {

            result.push_back(
                std::stof(value)
            );
        }
    }

    return result;
}


// =========================================================
// Escape JSON strings
// =========================================================

std::string escapeJson(
    const std::string& input
) {

    std::string output;

    for (char c : input) {

        switch (c) {

            case '\"':
                output += "\\\"";
                break;

            case '\\':
                output += "\\\\";
                break;

            case '\n':
                output += "\\n";
                break;

            case '\r':
                output += "\\r";
                break;

            case '\t':
                output += "\\t";
                break;

            default:
                output += c;
                break;
        }
    }

    return output;
}


// =========================================================
// Current UTC timestamp
//
// Example:
// 2026-08-11T08:00:00Z
// =========================================================

std::string currentTimestamp() {

    std::time_t now =
        std::time(nullptr);

    std::tm utcTime{};

#if defined(_WIN32)

    gmtime_s(
        &utcTime,
        &now
    );

#else

    gmtime_r(
        &now,
        &utcTime
    );

#endif

    std::ostringstream timestamp;

    timestamp
        << std::put_time(
            &utcTime,
            "%Y-%m-%dT%H:%M:%SZ"
        );

    return timestamp.str();
}


int main() {

    // =====================================================
    // Vector Database
    //
    // all-MiniLM-L6-v2 = 384 dimensions
    // =====================================================

    VectorDB db(384);

    httplib::Server server;


    // =====================================================
    // GET /health
    // =====================================================

    server.Get(
        "/health",
        [&](const httplib::Request&,
            httplib::Response& res) {

            res.set_content(
                R"({"status":"ok","service":"RecallAI Vector Engine"})",
                "application/json"
            );
        }
    );


    // =====================================================
    // GET /stats
    // =====================================================

    server.Get(
        "/stats",
        [&](const httplib::Request&,
            httplib::Response& res) {

            std::ostringstream json;

            json << "{";
            json << "\"count\":" << db.size();
            json << "}";

            res.set_content(
                json.str(),
                "application/json"
            );
        }
    );


    // =====================================================
    // GET /next-id
    //
    // Next vector ID
    // =====================================================

    server.Get(
        "/next-id",
        [&](const httplib::Request&,
            httplib::Response& res) {

            std::ostringstream json;

            json << "{";
            json << "\"next_id\":"
                 << db.nextId();
            json << "}";

            res.set_content(
                json.str(),
                "application/json"
            );
        }
    );


    // =====================================================
    // GET /next-document-id
    //
    // Next document ID
    // =====================================================

    server.Get(
        "/next-document-id",
        [&](const httplib::Request&,
            httplib::Response& res) {

            std::ostringstream json;

            json << "{";
            json << "\"next_document_id\":"
                 << db.nextDocumentId();
            json << "}";

            res.set_content(
                json.str(),
                "application/json"
            );
        }
    );


    // =====================================================
    // POST /documents
    //
    // Create a document.
    //
    // Required:
    //   filename
    //
    // upload_time is generated by the C++ engine.
    //
    // Example:
    //
    // POST /documents?filename=book.pdf
    // =====================================================

    server.Post(
        "/documents",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                // -------------------------------------------------
                // Validate filename
                // -------------------------------------------------

                if (!req.has_param("filename")) {

                    res.status = 400;

                    res.set_content(
                        R"({"error":"filename is required"})",
                        "application/json"
                    );

                    return;
                }


                std::string filename =
                    req.get_param_value(
                        "filename"
                    );


                if (filename.empty()) {

                    res.status = 400;

                    res.set_content(
                        R"({"error":"filename cannot be empty"})",
                        "application/json"
                    );

                    return;
                }


                // -------------------------------------------------
                // Generate upload timestamp
                // -------------------------------------------------

                std::string uploadTime =
                    currentTimestamp();


                // -------------------------------------------------
                // Create document
                // -------------------------------------------------

                int documentId =
                    db.addDocument(
                        filename,
                        uploadTime
                    );


                // -------------------------------------------------
                // Response
                // -------------------------------------------------

                std::ostringstream json;

                json << "{";

                json << "\"status\":\"created\",";

                json << "\"document\":{";

                json << "\"id\":"
                     << documentId
                     << ",";

                json << "\"filename\":\""
                     << escapeJson(filename)
                     << "\",";

                json << "\"upload_time\":\""
                     << escapeJson(uploadTime)
                     << "\",";

                json << "\"chunks\":0";

                json << "}";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(e.what())
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // GET /documents
    //
    // Return all documents.
    // =====================================================

    server.Get(
        "/documents",
        [&](const httplib::Request&,
            httplib::Response& res) {

            try {

                auto documents =
                    db.getDocuments();


                std::ostringstream json;

                json << "{";

                json << "\"documents\":[";


                for (
                    size_t i = 0;
                    i < documents.size();
                    i++
                ) {

                    if (i > 0) {
                        json << ",";
                    }


                    const auto& document =
                        documents[i];


                    json << "{";

                    json << "\"id\":"
                         << document.id
                         << ",";

                    json << "\"filename\":\""
                         << escapeJson(
                                document.filename
                            )
                         << "\",";

                    json << "\"upload_time\":\""
                         << escapeJson(
                                document.uploadTime
                            )
                         << "\",";

                    json << "\"chunks\":"
                         << document.vectorIds.size();


                    json << "}";
                }


                json << "]";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(e.what())
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // GET /documents/:id
    //
    // Return one document and its chunks.
    //
    // Example:
    // GET /documents/1
    // =====================================================

    server.Get(
        R"(/documents/(\d+))",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                int documentId =
                    std::stoi(
                        req.matches[1].str()
                    );


                const DocumentRecord* document =
                    db.getDocument(
                        documentId
                    );


                if (document == nullptr) {

                    res.status = 404;

                    res.set_content(
                        R"({"error":"Document not found"})",
                        "application/json"
                    );

                    return;
                }


                std::ostringstream json;

                json << "{";

                json << "\"id\":"
                     << document->id
                     << ",";

                json << "\"filename\":\""
                     << escapeJson(
                            document->filename
                        )
                     << "\",";

                json << "\"upload_time\":\""
                     << escapeJson(
                            document->uploadTime
                        )
                     << "\",";

                json << "\"chunks\":[";


                for (
                    size_t i = 0;
                    i < document->vectorIds.size();
                    i++
                ) {

                    if (i > 0) {
                        json << ",";
                    }


                    int vectorId =
                        document->vectorIds[i];


                    const VectorRecord* record =
                        db.get(
                            vectorId
                        );


                    if (record == nullptr) {
                        continue;
                    }


                    json << "{";

                    json << "\"vector_id\":"
                         << record->id
                         << ",";

                    json << "\"page\":"
                         << record->page
                         << ",";

                    json << "\"chunk\":"
                         << record->chunk;

                    json << "}";
                }


                json << "]";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(e.what())
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // DELETE /documents/:id
    //
    // Deletes the document AND all its chunks.
    //
    // Example:
    // DELETE /documents/1
    // =====================================================

    server.Delete(
        R"(/documents/(\d+))",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                int documentId =
                    std::stoi(
                        req.matches[1].str()
                    );


                bool deleted =
                    db.deleteDocument(
                        documentId
                    );


                if (!deleted) {

                    res.status = 404;

                    res.set_content(
                        R"({"error":"Document not found"})",
                        "application/json"
                    );

                    return;
                }


                std::ostringstream json;

                json << "{";

                json << "\"status\":\"deleted\",";

                json << "\"document_id\":"
                     << documentId;

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(e.what())
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // POST /insert
    //
    // Insert one vector/chunk into a document.
    //
    // Required parameters:
    //
    //   id
    //   document_id
    //   text
    //   source
    //   page
    //   chunk
    //
    // Vector:
    //   request body
    //
    // Example:
    //
    // POST /insert?id=1&document_id=1&...
    //
    // Body:
    // 0.123,0.456,...
    // =====================================================

    server.Post(
        "/insert",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                // -------------------------------------------------
                // Validate metadata
                // -------------------------------------------------

                if (
                    !req.has_param("id") ||
                    !req.has_param("document_id") ||
                    !req.has_param("text") ||
                    !req.has_param("source") ||
                    !req.has_param("page") ||
                    !req.has_param("chunk")
                ) {

                    res.status = 400;

                    res.set_content(
                        R"({"error":"id, document_id, text, source, page and chunk are required"})",
                        "application/json"
                    );

                    return;
                }


                // -------------------------------------------------
                // IDs
                // -------------------------------------------------

                int id =
                    std::stoi(
                        req.get_param_value("id")
                    );


                int documentId =
                    std::stoi(
                        req.get_param_value(
                            "document_id"
                        )
                    );


                // -------------------------------------------------
                // Parse vector
                // -------------------------------------------------

                std::vector<float> vector;


                if (!req.body.empty()) {

                    vector =
                        parseVector(
                            req.body
                        );
                }

                else if (req.has_param("vector")) {

                    vector =
                        parseVector(
                            req.get_param_value(
                                "vector"
                            )
                        );
                }

                else {

                    throw std::invalid_argument(
                        "vector is required"
                    );
                }


                // -------------------------------------------------
                // Metadata
                // -------------------------------------------------

                std::string text =
                    req.get_param_value(
                        "text"
                    );


                std::string source =
                    req.get_param_value(
                        "source"
                    );


                int page =
                    std::stoi(
                        req.get_param_value(
                            "page"
                        )
                    );


                int chunk =
                    std::stoi(
                        req.get_param_value(
                            "chunk"
                        )
                    );


                // -------------------------------------------------
                // Insert
                // -------------------------------------------------

                db.insert(
                    id,
                    documentId,
                    vector,
                    text,
                    source,
                    page,
                    chunk
                );


                // -------------------------------------------------
                // Response
                // -------------------------------------------------

                std::ostringstream json;

                json << "{";

                json << "\"status\":\"inserted\",";

                json << "\"id\":"
                     << id
                     << ",";

                json << "\"document_id\":"
                     << documentId;

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(
                            e.what()
                        )
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // GET /get
    //
    // Get one vector/chunk.
    //
    // Example:
    // GET /get?id=1
    // =====================================================

    server.Get(
        "/get",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                if (!req.has_param("id")) {

                    res.status = 400;

                    res.set_content(
                        R"({"error":"id is required"})",
                        "application/json"
                    );

                    return;
                }


                int id =
                    std::stoi(
                        req.get_param_value("id")
                    );


                const VectorRecord* record =
                    db.get(id);


                if (record == nullptr) {

                    res.status = 404;

                    res.set_content(
                        R"({"error":"Vector not found"})",
                        "application/json"
                    );

                    return;
                }


                std::ostringstream json;

                json << "{";

                json << "\"id\":"
                     << record->id
                     << ",";

                json << "\"document_id\":"
                     << record->documentId
                     << ",";

                json << "\"text\":\""
                     << escapeJson(
                            record->text
                        )
                     << "\",";

                json << "\"source\":\""
                     << escapeJson(
                            record->source
                        )
                     << "\",";

                json << "\"page\":"
                     << record->page
                     << ",";

                json << "\"chunk\":"
                     << record->chunk;

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(
                            e.what()
                        )
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // POST /search
    //
    // Query vector:
    //   request body
    //
    // Parameters:
    //   k
    //   algorithm
    //   metric
    //
    // Example:
    //
    // POST /search?k=5&algorithm=hnsw&metric=cosine
    //
    // Body:
    // 384 comma-separated floats
    // =====================================================

    server.Post(
        "/search",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                // -------------------------------------------------
                // Query vector
                // -------------------------------------------------

                std::vector<float> query;


                if (!req.body.empty()) {

                    query =
                        parseVector(
                            req.body
                        );
                }

                else if (req.has_param("query")) {

                    query =
                        parseVector(
                            req.get_param_value(
                                "query"
                            )
                        );
                }

                else {

                    throw std::invalid_argument(
                        "query vector is required"
                    );
                }


                // -------------------------------------------------
                // k
                // -------------------------------------------------

                int k = 5;


                if (req.has_param("k")) {

                    k =
                        std::stoi(
                            req.get_param_value("k")
                        );
                }


                // -------------------------------------------------
                // Algorithm
                // -------------------------------------------------

                std::string algorithm =
                    "hnsw";


                if (req.has_param("algorithm")) {

                    algorithm =
                        req.get_param_value(
                            "algorithm"
                        );
                }


                // -------------------------------------------------
                // Metric
                // -------------------------------------------------

                std::string metric =
                    "cosine";


                if (req.has_param("metric")) {

                    metric =
                        req.get_param_value(
                            "metric"
                        );
                }


                // -------------------------------------------------
                // Search
                // -------------------------------------------------

                auto results =
                    db.search(
                        query,
                        k,
                        algorithm,
                        metric
                    );


                // -------------------------------------------------
                // JSON response
                // -------------------------------------------------

                std::ostringstream json;

                json << "{";

                json << "\"algorithm\":\""
                     << escapeJson(
                            algorithm
                        )
                     << "\",";

                json << "\"metric\":\""
                     << escapeJson(
                            metric
                        )
                     << "\",";

                json << "\"results\":[";


                for (
                    size_t i = 0;
                    i < results.size();
                    i++
                ) {

                    if (i > 0) {
                        json << ",";
                    }


                    float distance =
                        results[i].first;


                    int id =
                        results[i].second;


                    const VectorRecord* record =
                        db.get(id);


                    json << "{";

                    json << "\"id\":"
                         << id
                         << ",";

                    json << "\"distance\":"
                         << distance
                         << ",";


                    if (record != nullptr) {

                        json << "\"document_id\":"
                             << record->documentId
                             << ",";

                        json << "\"text\":\""
                             << escapeJson(
                                    record->text
                                )
                             << "\",";

                        json << "\"source\":\""
                             << escapeJson(
                                    record->source
                                )
                             << "\",";

                        json << "\"page\":"
                             << record->page
                             << ",";

                        json << "\"chunk\":"
                             << record->chunk;
                    }

                    else {

                        json << "\"document_id\":0,";
                        json << "\"text\":\"\",";
                        json << "\"source\":\"\",";
                        json << "\"page\":0,";
                        json << "\"chunk\":0";
                    }


                    json << "}";
                }


                json << "]";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(
                            e.what()
                        )
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // DELETE /vectors/:id
    //
    // Deletes one vector/chunk.
    //
    // Example:
    // DELETE /vectors/5
    // =====================================================

    server.Delete(
        R"(/vectors/(\d+))",
        [&](const httplib::Request& req,
            httplib::Response& res) {

            try {

                int id =
                    std::stoi(
                        req.matches[1].str()
                    );


                bool removed =
                    db.erase(id);


                if (!removed) {

                    res.status = 404;

                    res.set_content(
                        R"({"error":"Vector not found"})",
                        "application/json"
                    );

                    return;
                }


                std::ostringstream json;

                json << "{";

                json << "\"status\":\"deleted\",";

                json << "\"id\":"
                     << id;

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }

            catch (const std::exception& e) {

                res.status = 400;

                std::ostringstream json;

                json << "{";

                json << "\"error\":\""
                     << escapeJson(
                            e.what()
                        )
                     << "\"";

                json << "}";


                res.set_content(
                    json.str(),
                    "application/json"
                );
            }
        }
    );


    // =====================================================
    // Start server
    // =====================================================

    std::cout
        << "RecallAI Vector Engine\n\n";

    std::cout
        << "http://localhost:8081\n\n";


    server.listen(
        "0.0.0.0",
        8081
    );

    return 0;
}